openapi: 3.0.1
info:
  title: API V1
  version: v1
tags:
- name: Lookup Items
  description: Endpoints for lookup items
security:
- bearerAuth: []
paths:
  "/api/lookup_items/countries":
    get:
      tags:
      - Lookup Items
      summary: list countries
      operationId: GetCountries
      responses:
        200:
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Country"
              example:
              - id: "123e4567-e89b-12d3-a456-426614174000"
                value: "United Kingdom"
                iso_code: "GB"
              - id: "223e4567-e89b-12d3-a456-426614174001"
                value: "France"
                iso_code: "FR"
        401:
          $ref: "#/components/responses/Unauthorized"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: 'API token passed as `Authorization: Bearer <token>`'
  schemas:
    Country:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        iso_code:
          type: string
      required:
      - id
      - value
      - iso_code
    PickListItem:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
      required:
      - id
      - value
  responses:
    Unauthorized:
      description: unauthorized
      content:
        application/json:
          example:
            errors:
            - error: Unauthorized
              message: Please provide a valid authentication token
servers:
- url: http://localhost:3000
