default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: get_into_teaching_interface_api_development
test:
  <<: *default
  database: get_into_teaching_interface_api_test

production:
  primary: &primary_production
    <<: *default
    database: get_into_teaching_interface_api_production
    username: get_into_teaching_interface_api
    password: <%= ENV["DB_PASSWORD"] %>
    sslmode: <%= ENV.fetch("DB_SSLMODE") { "require" } %>
