### Candidate Adviser eligibilities
GET http://localhost:3000/api/pick_list_items/candidate/adviser_eligibilities

### Candidate Adviser eligibilities with forced cache miss
GET http://localhost:3000/api/pick_list_items/candidate/adviser_eligibilities?force_cache_miss=true
