### Candidate Visa statuses
GET http://localhost:3000/api/pick_list_items/candidate/visa_statuses

### Candidate Visa statuses with forced cache miss
GET http://localhost:3000/api/pick_list_items/candidate/visa_statuses?force_cache_miss=true
