### Qualification Types
GET http://localhost:3000/api/pick_list_items/qualification/types

### Qualification Types with forced cache miss
GET http://localhost:3000/api/pick_list_items/qualification/types?force_cache_miss=true
